configbootstrap_http.go
The logic for looping during bootstrap was changed to correctly loop multiple nodes.  In order to correctly stop looping when some fatal errors occur, we need to specially handle these.
=> Fixed bootstrap to directly return BucketNotFound errors.

cbsearchx/queries.go
The JSON encoding of the request was missing the `start` and `end` fields which are necessary for date range search queries
=> Add start and end fields in date range search query request

agent.go
It previously was configured to use the FastFailRetryManager by default for an unknown reason in a9a0ae4be26bad85f961f256a2f29735266c7af9.
=> ING-479: Updated the DefaultRetryManager to be the default.

crud.go, crud_test.go, mock_vbucketrouter_test.go, vbucketmap.go, vbucketrouter.go
This also renames 'ReplicaIdx' throughout our vbucket dispatch code to be 'vbServerIdx' to disambiguate between replica index and vbucket server index.
=> #128: Fixed ReplicaIdx indexing error with GetReplica.

memdx/packetwriter.go
Motivation
----------
On the write side of writing to the connection anything which causes the validation of the packet to fail should be an invalid args error rather than a protocol error. It means that there is an issue in the user's packet rather than a protocol issue like there would be for a response packet.
Changes
-------
Updated WritePacket to return invalid argument errors on packet validation failure.
=> ING-590: Return invalid args error on write packet validation fail

bucketswatcher_http.go, bucketswatcher_http_test.go
Motivation
----------
At the moment if a user calls GetAgent when the tracker is handling detection of new buckets then the call will always block until all new agents are created and old ones destroyed. We should add a fast map so that requests for agents that we already know about can be resolved without waiting for a global lock.
=> ING-572: Add a fast map to buckets tracking http

cbqueryx/errors.go, cbqueryx/query_test.go, cbqueryx/queryrespreader.go, cbqueryx/utils_test.go
Motivation
----------
We need to expose index exists and not found from cbqueryx, and add handling for their respective error codes. This will enable users to be able to handle these errors without having to manually parse the error that we return.
=> ING-598: Add handling for index exists/not found to cbqueryx

cbmgmtx/mgmt.go, cbmgmtx/mgmt_test.go
Motivation
----------
We currently check if ReplicaIndexDisabled is set, and for ephemeral buckets return an error if so. We should just ignore this field for ephemeral buckets. It's completely reasonable for a user to set the value to true as the server will not allow the replicaIndex field to be set, so it would be expected that setting the field to true could lead to the parameter being omitted in the request. As we cannot distinguish false and not set for the field we cannot take any taken there either.
=> ING-591: Do not check if ReplicaIndexDisabled for ephemeral buckets

agent.go
Motivation
----------
At the moment we always use CCCP polling, for agents with no buckets we do not create any memcached connections. This means that those agents never receive config updates. We should use HTTP polling for those agents.
=> ING-603: Use HTTP poller for cluster level agents

cbqueryx/errors.go, cbqueryx/preparedquery.go, cbqueryx/preparedquery_test.go, cbqueryx/query.go, cbqueryx/query_json.go, cbqueryx/query_options.go, cbqueryx/query_options_test.go, cbqueryx/query_results.go, cbqueryx/query_test.go, cbqueryx/queryrespreader.go, cbqueryx/utils_test.go, querycomponent.go
Currently there are various types in cbqueryx that are prefixed with Query. This results in the types, when called outside of the package taking the form: `cbquery.Query` which is somewhat redundant.
=> ING-580 Remove Query prefix from cbqueryx types

cbqueryx/query_json.go, cbqueryx/query_options.go
A recent change was made to remove the Query prefix from  cbqueryx types. There are a few constants with the same Query prefix that lead to the same cbqueryx.Query pattern, these should also be changed
=> ING-621 Remove Query prefix from cbqueryx constants

memdx/errors.go, memdx/ops_crud.go
Currently when we attempt to perform concurrent mutate operations with insert semantics we get an internal server error returned to the User. Instead we should handle the status and return a more useful error to STG
=> ING-624 Handle SyncWriteInProgress status

memdx/errors.go, memdx/ops_crud.go
Currently if gocbcorex receives a a SyncRecommitInProgress status this will not be handled by gocbcorex and an unknown error will be returned. Instead we should handle this status and return an appropriate error.
=> ING-630 Handle SyncWriteReCommitInProgress status

memdx/errors.go, memdx/ops_crud.go
MutateIn with Insert semantics can return NotStored. This should be changed so that we handle NotStored in gocbcorex for a MutateIn with Insert semantics by converting it into a DocAlreadyExists error.
=> ING-453 Return DocExistsErr when NotStored status returned from MutateIn

.github/workflows/lint.yml
This resolves an issue with being able to scan one of the new commits.
=> Updated golangci-lint version.

cbmgmtx/errors.go, cbmgmtx/mgmt.go, cbmgmtx/mgmt_test.go
In order to make the errors returned by stellar-gateway more informative we first need to make the errors returned by gocbcorex distinguishable for the cases highlighted in ING-500
=> ING-500 Add new errors to propagate to stellar-gateway

agent.go
Motivation
----------
At the moment the config watcher is started before all of the agent components have been assigned. This can lead to a data race between assigning them and applying a config.
=> ING-659: Move where agent config watcher is started

.github/workflows/tests.yml
Tests can randomly fail due to our usage of cbdinocluster impacting tests within different packages running in parallel.
=> Limit tests in CI to only run a single package at a time

agent_ops.go, cbmgmtx/mgmt.go, mgmtcomponent.go
I had to add the special error parsing as the errors returned from the server is different between 7.2 `({"errors":{"history":"bucket must have storage_mode=magma, not couchstore"}})` and 7.6 `not allowed on this type of bucket`
WIP as awainting the merge of related Protostellar changes
=> ING-656: Support collection updating

cbsearchx/search.go
When performing document analysis against a scoped search index we currently construct the URI as with other search index operations. This leads to a page that does not exist, instead we need to include the fully qualified index name in the URI. The test to validate this works is being added in ING-677.
=> ING-717: Correct analyse doc URI construction

cbsearchx/errors.go, cbsearchx/search.go
There are a few FTS errors that are not parsed by gocbcorex, resulting in an unknown error status being returned to the User. This PR addresses such cases.
=> ING-715: More useful FTS errors

cbmgmtx/mgmt.go
Note that this is probably considered a bug, and I have added a bug line referring to the underlying MB.
=> ING-751: Added handling for new bucket not found error.

retrymanager_default.go
Previously we would retry operations every 1ms forever, now it will retry after 10ms, 20ms, 40ms, 80ms, etc...
=> ING-754: Fix exponential-backoff retry handling.

agent_int_test.go, agent_ops_int_test.go, agent_ops_rangescan_int_test.go, agentmanager_int_test.go, bucketswatcher_http_int_test.go, kvclient_int_test.go, kvclientmanager_int_test.go, kvclientpool_int_test.go, memdx/harness_int_test.go
After a few attempts I couldn't identify where the leak in the ticket came from. So have added more granular checking for leaks at the end of tests which could have caused this.
=> ING-689: Check for goroutine leaks at the end of integration tests

bucketstracking_agentmanager.go, kvclientpool.go
This adds throttling for connecting clients in a kvClientPool such that quickly errors do not lead to spamming connection attempts.  We also updated the logging around client management to make it easier to diagnose faults related to connections in the future.
=> ING-790: Added connection error throttling and improved logging.

.github/workflows/tests.yml, agent_ops.go, crud.go, crud_int_test.go, docs/REPLICA_READ.md, errors.go, go.mod, mock_vbucketrouter_test.go, retrymanager_getallreplicas.go, vbucketrouter.go
The logic here starts a thread for each replica that should exist according to NUM_REPLICAS. The overall GetAllReplicas operation is complete when NUM_REPLICAS + 1 docs have been returned, or it hits the timeout. The individual threads will run indefinitely until these points, even if the thread has returned a document. This is because the individual requests are routed based on the replica ID, which can be routed to a different node if there is a rebalance during the GetAllReplicas.
=> ING-523: Improve GetAllReplicas handling

.github/workflows/lint.yml, agent.go, agent_options.go, memdx/conn.go
Read buffering significantly reduces the costs of our reads by reducing the number of syscalls that need to be made.  Enabling NAGLE improves network efficiency, though this should ultimately be performed from inside gocbcorex at some point.  I saw better performance than enabling NAGLE by having a queue of packets to send and a goroutine which used a write buffer alongside deciding whether to flush it based on there being other data to write in the queue.
=> ING-942: Added read buffering and enable NAGLE in memdx.

configwatcher_memd.go, contrib/cbconfig/parse.go, crud_test.go, generate-mocks.go, kvclient.go, kvclient_ops.go, kvclient_test.go, kvclientmanager.go, kvclientmanager_test.go, kvclientpool.go, memdx/client.go, memdx/conn.go, memdx/dispatcher.go, memdx/errors.go, memdx/errors_test.go, memdx/harness_int_test.go, memdx/ops_core.go, memdx/ops_core_errors_test.go, memdx/ops_crud.go, memdx/ops_crud_int_test.go, memdx/ops_crud_rangescan.go, memdx/ops_utils.go, memdxclient.go, mock_kvclient_test.go, utils.go, vbucketrouter.go
This commit also refactors how we deal with remote hostnames and addresses with the various clients and connections inside of the library.  Primarily with the intent of simplifying the interfaces that we expose, and ensuring the correct details are available in the right places.
=> ING-959: Refactored hostname handling when parsing configs.

memdx/errors.go, memdx/ops_crud.go, memdx/ops_crud_int_test.go, memdx/status.go
We previously have always called this BadDelta, but this name is not accurate for what this error is actually used for from memcached.
=> ING-989: Fixed memd status code 0x6 to be DeltaBadval.

retrymanager_default.go
FTS folks confirmed that retrying `no planned pIndexes` is reasonable since we are already ensuring that the index is present on all of the nodes.
=> ING-1171: Retry no planned pIndexes error
